from enum import Enum

class EventType(Enum):
    EVENT_FILE_OPEN_AND_WRITE_EXIT = 1
    EVENT_FILE_OPEN_AND_READ_EXIT = 2
    EVENT_EXECVE = 3
    EVENT_PROCESS_EXIT = 4
    EVENT_INODE_SETATTR = 5
    EVENT_INODE_CREATE = 6
    EVENT_INODE_LINK = 7
    EVENT_INODE_SYMLINK = 8
    EVENT_INODE_MKDIR = 9
    EVENT_INODE_RMDIR = 10
    EVENT_INODE_MKNOD = 11
    EVENT_INODE_RENAME = 12
    EVENT_AUTH = 13
    EVENT_PASSWD_CHANGE = 14
    EVENT_CHANGE_USER = 15
    EVENT_SOCKET_CREATION = 16
    EVENT_SOCKET_BIND = 17
    EVENT_SOCKET_CONNECT_OUTBOUND = 18
    EVENT_SOCKET_LISTEN = 19
    EVENT_SOCKET_ACCEPT = 20
    
